setup:
  run_name: test

training:
  parallelism:
    num_gpus: 1
    accumulate_batches: 2
    batch_size: 16

  options:
    epochs: 3
    warmup_frac: 0.1
    float16: false
    test_every: 1000

  optimizer:
    lr: 1.0e-4

# These are passed directly to the model during initialization
model:
  normalization_groups: 32
  in_channels: 3
  out_channels: 3
  channels: 256
  num_head_channels: 64
  num_residuals: 6
  channel_multiple_schedule: [1, 2, 3]
  interior_attention: 1